# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\eyeon\repos\epp\src\_ui\add_shot_from_media.ui'
#
# Created: Wed Jun 05 14:29:02 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_dlgAddShotFromMedia(object):
    def setupUi(self, dlgAddShotFromMedia):
        dlgAddShotFromMedia.setObjectName("dlgAddShotFromMedia")
        dlgAddShotFromMedia.resize(425, 405)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/epp_128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlgAddShotFromMedia.setWindowIcon(icon)
        self.verticalLayout_2 = QtGui.QVBoxLayout(dlgAddShotFromMedia)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblHeader = QtGui.QLabel(dlgAddShotFromMedia)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lblHeader.setFont(font)
        self.lblHeader.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.lblHeader.setMargin(10)
        self.lblHeader.setObjectName("lblHeader")
        self.verticalLayout_2.addWidget(self.lblHeader)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(12, 9, 15, 24)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout1 = QtGui.QGridLayout()
        self.gridLayout1.setObjectName("gridLayout1")
        self._lblNamePreview = QtGui.QLabel(dlgAddShotFromMedia)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._lblNamePreview.sizePolicy().hasHeightForWidth())
        self._lblNamePreview.setSizePolicy(sizePolicy)
        self._lblNamePreview.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self._lblNamePreview.setFont(font)
        self._lblNamePreview.setObjectName("_lblNamePreview")
        self.gridLayout1.addWidget(self._lblNamePreview, 4, 0, 1, 1)
        self._lblProject = QtGui.QLabel(dlgAddShotFromMedia)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._lblProject.sizePolicy().hasHeightForWidth())
        self._lblProject.setSizePolicy(sizePolicy)
        self._lblProject.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self._lblProject.setFont(font)
        self._lblProject.setObjectName("_lblProject")
        self.gridLayout1.addWidget(self._lblProject, 1, 0, 1, 1)
        self.lblProject = QtGui.QLabel(dlgAddShotFromMedia)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProject.sizePolicy().hasHeightForWidth())
        self.lblProject.setSizePolicy(sizePolicy)
        self.lblProject.setText("")
        self.lblProject.setObjectName("lblProject")
        self.gridLayout1.addWidget(self.lblProject, 1, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout1.addItem(spacerItem, 2, 0, 1, 1)
        self._lblParsingPattern = QtGui.QLabel(dlgAddShotFromMedia)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self._lblParsingPattern.setFont(font)
        self._lblParsingPattern.setObjectName("_lblParsingPattern")
        self.gridLayout1.addWidget(self._lblParsingPattern, 3, 0, 1, 1)
        self.cmbParsingPattern = QtGui.QComboBox(dlgAddShotFromMedia)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbParsingPattern.sizePolicy().hasHeightForWidth())
        self.cmbParsingPattern.setSizePolicy(sizePolicy)
        self.cmbParsingPattern.setObjectName("cmbParsingPattern")
        self.gridLayout1.addWidget(self.cmbParsingPattern, 3, 2, 1, 1)
        self.lblNamePreview = QtGui.QLabel(dlgAddShotFromMedia)
        self.lblNamePreview.setText("")
        self.lblNamePreview.setObjectName("lblNamePreview")
        self.gridLayout1.addWidget(self.lblNamePreview, 4, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout1.addItem(spacerItem1, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout1)
        self.line = QtGui.QFrame(dlgAddShotFromMedia)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self._lblDirStructure = QtGui.QLabel(dlgAddShotFromMedia)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._lblDirStructure.sizePolicy().hasHeightForWidth())
        self._lblDirStructure.setSizePolicy(sizePolicy)
        self._lblDirStructure.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self._lblDirStructure.setFont(font)
        self._lblDirStructure.setObjectName("_lblDirStructure")
        self.gridLayout_3.addWidget(self._lblDirStructure, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 1, 1, 1)
        self._lblInsertPosition = QtGui.QLabel(dlgAddShotFromMedia)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self._lblInsertPosition.setFont(font)
        self._lblInsertPosition.setObjectName("_lblInsertPosition")
        self.gridLayout_3.addWidget(self._lblInsertPosition, 2, 0, 1, 1)
        self.cmbInsertPosition = QtGui.QComboBox(dlgAddShotFromMedia)
        self.cmbInsertPosition.setObjectName("cmbInsertPosition")
        self.cmbInsertPosition.addItem("")
        self.cmbInsertPosition.addItem("")
        self.gridLayout_3.addWidget(self.cmbInsertPosition, 2, 2, 1, 1)
        self.cmbDirStructure = QtGui.QComboBox(dlgAddShotFromMedia)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDirStructure.sizePolicy().hasHeightForWidth())
        self.cmbDirStructure.setSizePolicy(sizePolicy)
        self.cmbDirStructure.setObjectName("cmbDirStructure")
        self.gridLayout_3.addWidget(self.cmbDirStructure, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.lblStatus = QtGui.QLabel(dlgAddShotFromMedia)
        self.lblStatus.setStyleSheet("")
        self.lblStatus.setOpenExternalLinks(True)
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout.addWidget(self.lblStatus)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.butAdd = QtGui.QPushButton(dlgAddShotFromMedia)
        self.butAdd.setObjectName("butAdd")
        self.horizontalLayout_2.addWidget(self.butAdd)
        self.butCancel = QtGui.QPushButton(dlgAddShotFromMedia)
        self.butCancel.setObjectName("butCancel")
        self.horizontalLayout_2.addWidget(self.butCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self._lblDirStructure.setBuddy(self.cmbDirStructure)

        self.retranslateUi(dlgAddShotFromMedia)
        self.cmbInsertPosition.setCurrentIndex(0)
        QtCore.QObject.connect(self.butAdd, QtCore.SIGNAL("clicked()"), dlgAddShotFromMedia.accept)
        QtCore.QObject.connect(self.butCancel, QtCore.SIGNAL("clicked()"), dlgAddShotFromMedia.reject)
        QtCore.QMetaObject.connectSlotsByName(dlgAddShotFromMedia)
        dlgAddShotFromMedia.setTabOrder(self.cmbDirStructure, self.butAdd)
        dlgAddShotFromMedia.setTabOrder(self.butAdd, self.butCancel)

    def retranslateUi(self, dlgAddShotFromMedia):
        dlgAddShotFromMedia.setWindowTitle(QtGui.QApplication.translate("dlgAddShotFromMedia", "Add Shot from Media", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHeader.setText(QtGui.QApplication.translate("dlgAddShotFromMedia", "Add Shot from Media", None, QtGui.QApplication.UnicodeUTF8))
        self._lblNamePreview.setToolTip(QtGui.QApplication.translate("dlgAddShotFromMedia", "Project name and also the projects root directory name", None, QtGui.QApplication.UnicodeUTF8))
        self._lblNamePreview.setWhatsThis(QtGui.QApplication.translate("dlgAddShotFromMedia", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">The </span><span style=\" font-size:8pt; font-weight:600;\">Name</span><span style=\" font-size:8pt;\"> for the project needs to be set based on studio conventions. This name is also used for the root folder of the project. Make sure it is file system safe and does not contain invalid characters. The default widget limits input to valid characters. Already existing project names can not be used to prevent data loss through overwriting.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self._lblNamePreview.setText(QtGui.QApplication.translate("dlgAddShotFromMedia", "Name Preview", None, QtGui.QApplication.UnicodeUTF8))
        self._lblProject.setToolTip(QtGui.QApplication.translate("dlgAddShotFromMedia", "Format Template for production.", None, QtGui.QApplication.UnicodeUTF8))
        self._lblProject.setWhatsThis(QtGui.QApplication.translate("dlgAddShotFromMedia", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The <span style=\" font-weight:600;\">Format Templates</span> are presets of Width, Height, Framerage (FPS) and Aspect Ratios for a Production. They are stored in your <span style=\" font-style:italic;\">epp_root\\templates\\formats.xml</span> file. As starting point formats can be imported during install of epp from eyeon Fusion.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self._lblProject.setText(QtGui.QApplication.translate("dlgAddShotFromMedia", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self._lblParsingPattern.setText(QtGui.QApplication.translate("dlgAddShotFromMedia", "Parsing Pattern", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbParsingPattern.setToolTip(QtGui.QApplication.translate("dlgAddShotFromMedia", "Template for the created directory structure.", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbParsingPattern.setWhatsThis(QtGui.QApplication.translate("dlgAddShotFromMedia", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">The </span><span style=\" font-size:8pt; font-weight:600;\">Directory Structure</span><span style=\" font-size:8pt;\"> contains all xml files in the </span><span style=\" font-size:8pt; font-style:italic;\">epp_root\\templates\\project_dirs</span><span style=\" font-size:8pt;\"> subfolder. Each file represents a XML folder and file structure which will be created once the project is created.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self._lblDirStructure.setToolTip(QtGui.QApplication.translate("dlgAddShotFromMedia", "Template for the created directory structure.", None, QtGui.QApplication.UnicodeUTF8))
        self._lblDirStructure.setWhatsThis(QtGui.QApplication.translate("dlgAddShotFromMedia", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">The </span><span style=\" font-size:8pt; font-weight:600;\">Directory Structure</span><span style=\" font-size:8pt;\"> contains all xml files in the </span><span style=\" font-size:8pt; font-style:italic;\">epp_root\\templates\\project_dirs</span><span style=\" font-size:8pt;\"> subfolder. Each file represents a XML folder and file structure which will be created once the project is created.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self._lblDirStructure.setText(QtGui.QApplication.translate("dlgAddShotFromMedia", "Directory Structure", None, QtGui.QApplication.UnicodeUTF8))
        self._lblInsertPosition.setText(QtGui.QApplication.translate("dlgAddShotFromMedia", "Insert Position", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbInsertPosition.setItemText(0, QtGui.QApplication.translate("dlgAddShotFromMedia", "Top", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbInsertPosition.setItemText(1, QtGui.QApplication.translate("dlgAddShotFromMedia", "Bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbDirStructure.setToolTip(QtGui.QApplication.translate("dlgAddShotFromMedia", "Template for the created directory structure.", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbDirStructure.setWhatsThis(QtGui.QApplication.translate("dlgAddShotFromMedia", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">The </span><span style=\" font-size:8pt; font-weight:600;\">Directory Structure</span><span style=\" font-size:8pt;\"> contains all xml files in the </span><span style=\" font-size:8pt; font-style:italic;\">epp_root\\templates\\project_dirs</span><span style=\" font-size:8pt;\"> subfolder. Each file represents a XML folder and file structure which will be created once the project is created.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStatus.setStatusTip(QtGui.QApplication.translate("dlgAddShotFromMedia", "Warning Status", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStatus.setText(QtGui.QApplication.translate("dlgAddShotFromMedia", "WARINING", None, QtGui.QApplication.UnicodeUTF8))
        self.butAdd.setStatusTip(QtGui.QApplication.translate("dlgAddShotFromMedia", "Create Project and Directories", None, QtGui.QApplication.UnicodeUTF8))
        self.butAdd.setText(QtGui.QApplication.translate("dlgAddShotFromMedia", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.butCancel.setStatusTip(QtGui.QApplication.translate("dlgAddShotFromMedia", "Cancel the operation", None, QtGui.QApplication.UnicodeUTF8))
        self.butCancel.setText(QtGui.QApplication.translate("dlgAddShotFromMedia", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

import epp_rc
