# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\eyeon\repos\epp\src\_ui\add_project.ui'
#
# Created: Tue Mar 12 12:21:24 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_dlgAddProject(object):
    def setupUi(self, dlgAddProject):
        dlgAddProject.setObjectName("dlgAddProject")
        dlgAddProject.resize(425, 405)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/epp_128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlgAddProject.setWindowIcon(icon)
        self.verticalLayout_2 = QtGui.QVBoxLayout(dlgAddProject)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblHeader = QtGui.QLabel(dlgAddProject)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lblHeader.setFont(font)
        self.lblHeader.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.lblHeader.setMargin(10)
        self.lblHeader.setObjectName("lblHeader")
        self.verticalLayout_2.addWidget(self.lblHeader)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(12, 9, 15, 24)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout1 = QtGui.QGridLayout()
        self.gridLayout1.setObjectName("gridLayout1")
        self._lblName = QtGui.QLabel(dlgAddProject)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._lblName.sizePolicy().hasHeightForWidth())
        self._lblName.setSizePolicy(sizePolicy)
        self._lblName.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self._lblName.setFont(font)
        self._lblName.setObjectName("_lblName")
        self.gridLayout1.addWidget(self._lblName, 1, 0, 1, 1)
        self._lblFormatTemplate = QtGui.QLabel(dlgAddProject)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._lblFormatTemplate.sizePolicy().hasHeightForWidth())
        self._lblFormatTemplate.setSizePolicy(sizePolicy)
        self._lblFormatTemplate.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self._lblFormatTemplate.setFont(font)
        self._lblFormatTemplate.setObjectName("_lblFormatTemplate")
        self.gridLayout1.addWidget(self._lblFormatTemplate, 3, 0, 1, 1)
        self.cmbFormatTemplate = QtGui.QComboBox(dlgAddProject)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFormatTemplate.sizePolicy().hasHeightForWidth())
        self.cmbFormatTemplate.setSizePolicy(sizePolicy)
        self.cmbFormatTemplate.setStatusTip("")
        self.cmbFormatTemplate.setObjectName("cmbFormatTemplate")
        self.gridLayout1.addWidget(self.cmbFormatTemplate, 3, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout1.addItem(spacerItem, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout1)
        self.line = QtGui.QFrame(dlgAddProject)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setContentsMargins(20, -1, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self._lblWidth = QtGui.QLabel(dlgAddProject)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._lblWidth.sizePolicy().hasHeightForWidth())
        self._lblWidth.setSizePolicy(sizePolicy)
        self._lblWidth.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self._lblWidth.setFont(font)
        self._lblWidth.setObjectName("_lblWidth")
        self.gridLayout_2.addWidget(self._lblWidth, 0, 0, 1, 1)
        self._lblHeight = QtGui.QLabel(dlgAddProject)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._lblHeight.sizePolicy().hasHeightForWidth())
        self._lblHeight.setSizePolicy(sizePolicy)
        self._lblHeight.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self._lblHeight.setFont(font)
        self._lblHeight.setObjectName("_lblHeight")
        self.gridLayout_2.addWidget(self._lblHeight, 2, 0, 1, 1)
        self._lblFPS = QtGui.QLabel(dlgAddProject)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._lblFPS.sizePolicy().hasHeightForWidth())
        self._lblFPS.setSizePolicy(sizePolicy)
        self._lblFPS.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self._lblFPS.setFont(font)
        self._lblFPS.setObjectName("_lblFPS")
        self.gridLayout_2.addWidget(self._lblFPS, 3, 0, 1, 1)
        self.spnWidth = QtGui.QSpinBox(dlgAddProject)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnWidth.sizePolicy().hasHeightForWidth())
        self.spnWidth.setSizePolicy(sizePolicy)
        self.spnWidth.setMinimum(1)
        self.spnWidth.setMaximum(16000)
        self.spnWidth.setProperty("value", 1920)
        self.spnWidth.setObjectName("spnWidth")
        self.gridLayout_2.addWidget(self.spnWidth, 0, 2, 1, 1)
        self.spnHeight = QtGui.QSpinBox(dlgAddProject)
        self.spnHeight.setMinimum(1)
        self.spnHeight.setMaximum(16000)
        self.spnHeight.setProperty("value", 1080)
        self.spnHeight.setObjectName("spnHeight")
        self.gridLayout_2.addWidget(self.spnHeight, 2, 2, 1, 1)
        self.spnFPS = QtGui.QDoubleSpinBox(dlgAddProject)
        self.spnFPS.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.spnFPS.setPrefix("")
        self.spnFPS.setDecimals(3)
        self.spnFPS.setMaximum(9999.99)
        self.spnFPS.setProperty("value", 24.0)
        self.spnFPS.setObjectName("spnFPS")
        self.gridLayout_2.addWidget(self.spnFPS, 3, 2, 1, 1)
        self._lblAspect = QtGui.QLabel(dlgAddProject)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._lblAspect.sizePolicy().hasHeightForWidth())
        self._lblAspect.setSizePolicy(sizePolicy)
        self._lblAspect.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self._lblAspect.setFont(font)
        self._lblAspect.setObjectName("_lblAspect")
        self.gridLayout_2.addWidget(self._lblAspect, 4, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self._lblAspectX = QtGui.QLabel(dlgAddProject)
        self._lblAspectX.setObjectName("_lblAspectX")
        self.horizontalLayout.addWidget(self._lblAspectX)
        self.spnAspectX = QtGui.QDoubleSpinBox(dlgAddProject)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnAspectX.sizePolicy().hasHeightForWidth())
        self.spnAspectX.setSizePolicy(sizePolicy)
        self.spnAspectX.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.spnAspectX.setDecimals(3)
        self.spnAspectX.setSingleStep(0.1)
        self.spnAspectX.setProperty("value", 1.0)
        self.spnAspectX.setObjectName("spnAspectX")
        self.horizontalLayout.addWidget(self.spnAspectX)
        self._lblAspectY = QtGui.QLabel(dlgAddProject)
        self._lblAspectY.setObjectName("_lblAspectY")
        self.horizontalLayout.addWidget(self._lblAspectY)
        self.spnAspectY = QtGui.QDoubleSpinBox(dlgAddProject)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnAspectY.sizePolicy().hasHeightForWidth())
        self.spnAspectY.setSizePolicy(sizePolicy)
        self.spnAspectY.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.spnAspectY.setDecimals(3)
        self.spnAspectY.setSingleStep(0.1)
        self.spnAspectY.setProperty("value", 1.0)
        self.spnAspectY.setObjectName("spnAspectY")
        self.horizontalLayout.addWidget(self.spnAspectY)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line_2 = QtGui.QFrame(dlgAddProject)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self._lblDirStructure = QtGui.QLabel(dlgAddProject)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._lblDirStructure.sizePolicy().hasHeightForWidth())
        self._lblDirStructure.setSizePolicy(sizePolicy)
        self._lblDirStructure.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self._lblDirStructure.setFont(font)
        self._lblDirStructure.setObjectName("_lblDirStructure")
        self.gridLayout_3.addWidget(self._lblDirStructure, 1, 0, 1, 1)
        self.cmbDirStructure = QtGui.QComboBox(dlgAddProject)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDirStructure.sizePolicy().hasHeightForWidth())
        self.cmbDirStructure.setSizePolicy(sizePolicy)
        self.cmbDirStructure.setObjectName("cmbDirStructure")
        self.gridLayout_3.addWidget(self.cmbDirStructure, 1, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.lblStatus = QtGui.QLabel(dlgAddProject)
        self.lblStatus.setStyleSheet("")
        self.lblStatus.setOpenExternalLinks(True)
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout.addWidget(self.lblStatus)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.butAdd = QtGui.QPushButton(dlgAddProject)
        self.butAdd.setObjectName("butAdd")
        self.horizontalLayout_2.addWidget(self.butAdd)
        self.butCancel = QtGui.QPushButton(dlgAddProject)
        self.butCancel.setObjectName("butCancel")
        self.horizontalLayout_2.addWidget(self.butCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self._lblFormatTemplate.setBuddy(self.cmbFormatTemplate)
        self._lblWidth.setBuddy(self.spnWidth)
        self._lblHeight.setBuddy(self.spnHeight)
        self._lblFPS.setBuddy(self.spnFPS)
        self._lblAspectX.setBuddy(self.spnAspectX)
        self._lblAspectY.setBuddy(self.spnAspectY)
        self._lblDirStructure.setBuddy(self.cmbDirStructure)

        self.retranslateUi(dlgAddProject)
        QtCore.QObject.connect(self.butAdd, QtCore.SIGNAL("clicked()"), dlgAddProject.accept)
        QtCore.QObject.connect(self.butCancel, QtCore.SIGNAL("clicked()"), dlgAddProject.reject)
        QtCore.QMetaObject.connectSlotsByName(dlgAddProject)
        dlgAddProject.setTabOrder(self.cmbFormatTemplate, self.spnWidth)
        dlgAddProject.setTabOrder(self.spnWidth, self.spnHeight)
        dlgAddProject.setTabOrder(self.spnHeight, self.spnFPS)
        dlgAddProject.setTabOrder(self.spnFPS, self.cmbDirStructure)
        dlgAddProject.setTabOrder(self.cmbDirStructure, self.butAdd)
        dlgAddProject.setTabOrder(self.butAdd, self.butCancel)

    def retranslateUi(self, dlgAddProject):
        dlgAddProject.setWindowTitle(QtGui.QApplication.translate("dlgAddProject", "Add Project", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHeader.setText(QtGui.QApplication.translate("dlgAddProject", "Add Project", None, QtGui.QApplication.UnicodeUTF8))
        self._lblName.setToolTip(QtGui.QApplication.translate("dlgAddProject", "Project name and also the projects root directory name", None, QtGui.QApplication.UnicodeUTF8))
        self._lblName.setWhatsThis(QtGui.QApplication.translate("dlgAddProject", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">The </span><span style=\" font-size:8pt; font-weight:600;\">Name</span><span style=\" font-size:8pt;\"> for the project needs to be set based on studio conventions. This name is also used for the root folder of the project. Make sure it is file system safe and does not contain invalid characters. The default widget limits input to valid characters. Already existing project names can not be used to prevent data loss through overwriting.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self._lblName.setText(QtGui.QApplication.translate("dlgAddProject", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self._lblFormatTemplate.setToolTip(QtGui.QApplication.translate("dlgAddProject", "Format Template for production.", None, QtGui.QApplication.UnicodeUTF8))
        self._lblFormatTemplate.setWhatsThis(QtGui.QApplication.translate("dlgAddProject", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The <span style=\" font-weight:600;\">Format Templates</span> are presets of Width, Height, Framerage (FPS) and Aspect Ratios for a Production. They are stored in your <span style=\" font-style:italic;\">epp_root\\templates\\formats.xml</span> file. As starting point formats can be imported during install of epp from eyeon Fusion.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self._lblFormatTemplate.setText(QtGui.QApplication.translate("dlgAddProject", "Format Template", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFormatTemplate.setToolTip(QtGui.QApplication.translate("dlgAddProject", "Format Template for production.", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFormatTemplate.setWhatsThis(QtGui.QApplication.translate("dlgAddProject", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The <span style=\" font-weight:600;\">Format Templates</span> are presets of Width, Height, Framerage (FPS) and Aspect Ratios for a Production. They are stored in your <span style=\" font-style:italic;\">epp_root\\templates\\formats.xml</span> file. As starting point formats can be imported during install of epp from eyeon Fusion.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self._lblWidth.setToolTip(QtGui.QApplication.translate("dlgAddProject", "Image Resolution Width for project", None, QtGui.QApplication.UnicodeUTF8))
        self._lblWidth.setText(QtGui.QApplication.translate("dlgAddProject", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self._lblHeight.setToolTip(QtGui.QApplication.translate("dlgAddProject", "Image Resolution Height for project", None, QtGui.QApplication.UnicodeUTF8))
        self._lblHeight.setText(QtGui.QApplication.translate("dlgAddProject", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self._lblFPS.setToolTip(QtGui.QApplication.translate("dlgAddProject", "Framerate in frames per second (FPS).", None, QtGui.QApplication.UnicodeUTF8))
        self._lblFPS.setText(QtGui.QApplication.translate("dlgAddProject", "Framerate (FPS)", None, QtGui.QApplication.UnicodeUTF8))
        self.spnWidth.setToolTip(QtGui.QApplication.translate("dlgAddProject", "Image Resolution Width for project", None, QtGui.QApplication.UnicodeUTF8))
        self.spnHeight.setToolTip(QtGui.QApplication.translate("dlgAddProject", "Image Resolution Height for project", None, QtGui.QApplication.UnicodeUTF8))
        self.spnFPS.setToolTip(QtGui.QApplication.translate("dlgAddProject", "Framerate in frames per second (FPS).", None, QtGui.QApplication.UnicodeUTF8))
        self._lblAspect.setToolTip(QtGui.QApplication.translate("dlgAddProject", "Aspect Ratio. E.g. for anamorphic formats.", None, QtGui.QApplication.UnicodeUTF8))
        self._lblAspect.setText(QtGui.QApplication.translate("dlgAddProject", "Aspect Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self._lblAspectX.setToolTip(QtGui.QApplication.translate("dlgAddProject", "Aspect Ratio. E.g. for anamorphic formats.", None, QtGui.QApplication.UnicodeUTF8))
        self._lblAspectX.setText(QtGui.QApplication.translate("dlgAddProject", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.spnAspectX.setToolTip(QtGui.QApplication.translate("dlgAddProject", "Aspect Ratio. E.g. for anamorphic formats.", None, QtGui.QApplication.UnicodeUTF8))
        self._lblAspectY.setToolTip(QtGui.QApplication.translate("dlgAddProject", "Aspect Ratio. E.g. for anamorphic formats.", None, QtGui.QApplication.UnicodeUTF8))
        self._lblAspectY.setText(QtGui.QApplication.translate("dlgAddProject", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.spnAspectY.setToolTip(QtGui.QApplication.translate("dlgAddProject", "Aspect Ratio. E.g. for anamorphic formats.", None, QtGui.QApplication.UnicodeUTF8))
        self._lblDirStructure.setToolTip(QtGui.QApplication.translate("dlgAddProject", "Template for the created directory structure.", None, QtGui.QApplication.UnicodeUTF8))
        self._lblDirStructure.setWhatsThis(QtGui.QApplication.translate("dlgAddProject", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">The </span><span style=\" font-size:8pt; font-weight:600;\">Directory Structure</span><span style=\" font-size:8pt;\"> contains all xml files in the </span><span style=\" font-size:8pt; font-style:italic;\">epp_root\\templates\\project_dirs</span><span style=\" font-size:8pt;\"> subfolder. Each file represents a XML folder and file structure which will be created once the project is created.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self._lblDirStructure.setText(QtGui.QApplication.translate("dlgAddProject", "Directory Structure", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbDirStructure.setToolTip(QtGui.QApplication.translate("dlgAddProject", "Template for the created directory structure.", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbDirStructure.setWhatsThis(QtGui.QApplication.translate("dlgAddProject", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">The </span><span style=\" font-size:8pt; font-weight:600;\">Directory Structure</span><span style=\" font-size:8pt;\"> contains all xml files in the </span><span style=\" font-size:8pt; font-style:italic;\">epp_root\\templates\\project_dirs</span><span style=\" font-size:8pt;\"> subfolder. Each file represents a XML folder and file structure which will be created once the project is created.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStatus.setStatusTip(QtGui.QApplication.translate("dlgAddProject", "Warning Status", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStatus.setText(QtGui.QApplication.translate("dlgAddProject", "WARINING", None, QtGui.QApplication.UnicodeUTF8))
        self.butAdd.setStatusTip(QtGui.QApplication.translate("dlgAddProject", "Create Project and Directories", None, QtGui.QApplication.UnicodeUTF8))
        self.butAdd.setText(QtGui.QApplication.translate("dlgAddProject", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.butCancel.setStatusTip(QtGui.QApplication.translate("dlgAddProject", "Cancel the operation", None, QtGui.QApplication.UnicodeUTF8))
        self.butCancel.setText(QtGui.QApplication.translate("dlgAddProject", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

import epp_rc
