# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\eyeon\repos\epp\src\_ui\add_shot.ui'
#
# Created: Fri Feb 08 03:35:58 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_dlgAddShot(object):
    def setupUi(self, dlgAddShot):
        dlgAddShot.setObjectName("dlgAddShot")
        dlgAddShot.resize(425, 405)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/epp_128.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        dlgAddShot.setWindowIcon(icon)
        self.verticalLayout_2 = QtGui.QVBoxLayout(dlgAddShot)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblHeader = QtGui.QLabel(dlgAddShot)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lblHeader.setFont(font)
        self.lblHeader.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.lblHeader.setMargin(10)
        self.lblHeader.setObjectName("lblHeader")
        self.verticalLayout_2.addWidget(self.lblHeader)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(12, 9, 15, 24)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout1 = QtGui.QGridLayout()
        self.gridLayout1.setObjectName("gridLayout1")
        self._lblName = QtGui.QLabel(dlgAddShot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._lblName.sizePolicy().hasHeightForWidth())
        self._lblName.setSizePolicy(sizePolicy)
        self._lblName.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self._lblName.setFont(font)
        self._lblName.setObjectName("_lblName")
        self.gridLayout1.addWidget(self._lblName, 3, 0, 1, 1)
        self._lblProject = QtGui.QLabel(dlgAddShot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._lblProject.sizePolicy().hasHeightForWidth())
        self._lblProject.setSizePolicy(sizePolicy)
        self._lblProject.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self._lblProject.setFont(font)
        self._lblProject.setObjectName("_lblProject")
        self.gridLayout1.addWidget(self._lblProject, 1, 0, 1, 1)
        self.lblProject = QtGui.QLabel(dlgAddShot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblProject.sizePolicy().hasHeightForWidth())
        self.lblProject.setSizePolicy(sizePolicy)
        self.lblProject.setText("")
        self.lblProject.setObjectName("lblProject")
        self.gridLayout1.addWidget(self.lblProject, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout1.addItem(spacerItem, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout1)
        self.line = QtGui.QFrame(dlgAddShot)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self._lblDirStructure = QtGui.QLabel(dlgAddShot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._lblDirStructure.sizePolicy().hasHeightForWidth())
        self._lblDirStructure.setSizePolicy(sizePolicy)
        self._lblDirStructure.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self._lblDirStructure.setFont(font)
        self._lblDirStructure.setObjectName("_lblDirStructure")
        self.gridLayout_3.addWidget(self._lblDirStructure, 1, 0, 1, 1)
        self.cmbDirStructure = QtGui.QComboBox(dlgAddShot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDirStructure.sizePolicy().hasHeightForWidth())
        self.cmbDirStructure.setSizePolicy(sizePolicy)
        self.cmbDirStructure.setObjectName("cmbDirStructure")
        self.gridLayout_3.addWidget(self.cmbDirStructure, 1, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 1, 1, 1)
        self._lblInsertPosition = QtGui.QLabel(dlgAddShot)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self._lblInsertPosition.setFont(font)
        self._lblInsertPosition.setObjectName("_lblInsertPosition")
        self.gridLayout_3.addWidget(self._lblInsertPosition, 2, 0, 1, 1)
        self.cmbInsertPosition = QtGui.QComboBox(dlgAddShot)
        self.cmbInsertPosition.setObjectName("cmbInsertPosition")
        self.cmbInsertPosition.addItem("")
        self.cmbInsertPosition.addItem("")
        self.cmbInsertPosition.addItem("")
        self.gridLayout_3.addWidget(self.cmbInsertPosition, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.lblStatus = QtGui.QLabel(dlgAddShot)
        self.lblStatus.setStyleSheet("")
        self.lblStatus.setOpenExternalLinks(True)
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout.addWidget(self.lblStatus)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.chkAnother = QtGui.QCheckBox(dlgAddShot)
        self.chkAnother.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkAnother.setObjectName("chkAnother")
        self.horizontalLayout_2.addWidget(self.chkAnother)
        self.butAdd = QtGui.QPushButton(dlgAddShot)
        self.butAdd.setObjectName("butAdd")
        self.horizontalLayout_2.addWidget(self.butAdd)
        self.butCancel = QtGui.QPushButton(dlgAddShot)
        self.butCancel.setObjectName("butCancel")
        self.horizontalLayout_2.addWidget(self.butCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self._lblDirStructure.setBuddy(self.cmbDirStructure)

        self.retranslateUi(dlgAddShot)
        self.cmbInsertPosition.setCurrentIndex(2)
        QtCore.QObject.connect(self.butAdd, QtCore.SIGNAL("clicked()"), dlgAddShot.accept)
        QtCore.QObject.connect(self.butCancel, QtCore.SIGNAL("clicked()"), dlgAddShot.reject)
        QtCore.QMetaObject.connectSlotsByName(dlgAddShot)
        dlgAddShot.setTabOrder(self.cmbDirStructure, self.butAdd)
        dlgAddShot.setTabOrder(self.butAdd, self.butCancel)

    def retranslateUi(self, dlgAddShot):
        dlgAddShot.setWindowTitle(QtGui.QApplication.translate("dlgAddShot", "Add Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHeader.setText(QtGui.QApplication.translate("dlgAddShot", "Add Shot", None, QtGui.QApplication.UnicodeUTF8))
        self._lblName.setToolTip(QtGui.QApplication.translate("dlgAddShot", "Project name and also the projects root directory name", None, QtGui.QApplication.UnicodeUTF8))
        self._lblName.setWhatsThis(QtGui.QApplication.translate("dlgAddShot", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">The </span><span style=\" font-size:8pt; font-weight:600;\">Name</span><span style=\" font-size:8pt;\"> for the project needs to be set based on studio conventions. This name is also used for the root folder of the project. Make sure it is file system safe and does not contain invalid characters. The default widget limits input to valid characters. Already existing project names can not be used to prevent data loss through overwriting.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self._lblName.setText(QtGui.QApplication.translate("dlgAddShot", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self._lblProject.setToolTip(QtGui.QApplication.translate("dlgAddShot", "Format Template for production.", None, QtGui.QApplication.UnicodeUTF8))
        self._lblProject.setWhatsThis(QtGui.QApplication.translate("dlgAddShot", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The <span style=\" font-weight:600;\">Format Templates</span> are presets of Width, Height, Framerage (FPS) and Aspect Ratios for a Production. They are stored in your <span style=\" font-style:italic;\">epp_root\\templates\\formats.xml</span> file. As starting point formats can be imported during install of epp from eyeon Fusion.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self._lblProject.setText(QtGui.QApplication.translate("dlgAddShot", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self._lblDirStructure.setToolTip(QtGui.QApplication.translate("dlgAddShot", "Template for the created directory structure.", None, QtGui.QApplication.UnicodeUTF8))
        self._lblDirStructure.setWhatsThis(QtGui.QApplication.translate("dlgAddShot", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">The </span><span style=\" font-size:8pt; font-weight:600;\">Directory Structure</span><span style=\" font-size:8pt;\"> contains all xml files in the </span><span style=\" font-size:8pt; font-style:italic;\">epp_root\\templates\\project_dirs</span><span style=\" font-size:8pt;\"> subfolder. Each file represents a XML folder and file structure which will be created once the project is created.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self._lblDirStructure.setText(QtGui.QApplication.translate("dlgAddShot", "Directory Structure", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbDirStructure.setToolTip(QtGui.QApplication.translate("dlgAddShot", "Template for the created directory structure.", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbDirStructure.setWhatsThis(QtGui.QApplication.translate("dlgAddShot", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">The </span><span style=\" font-size:8pt; font-weight:600;\">Directory Structure</span><span style=\" font-size:8pt;\"> contains all xml files in the </span><span style=\" font-size:8pt; font-style:italic;\">epp_root\\templates\\project_dirs</span><span style=\" font-size:8pt;\"> subfolder. Each file represents a XML folder and file structure which will be created once the project is created.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self._lblInsertPosition.setText(QtGui.QApplication.translate("dlgAddShot", "Insert Position", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbInsertPosition.setItemText(0, QtGui.QApplication.translate("dlgAddShot", "Head", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbInsertPosition.setItemText(1, QtGui.QApplication.translate("dlgAddShot", "Tail", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbInsertPosition.setItemText(2, QtGui.QApplication.translate("dlgAddShot", "Alphabetically", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStatus.setStatusTip(QtGui.QApplication.translate("dlgAddShot", "Warning Status", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStatus.setText(QtGui.QApplication.translate("dlgAddShot", "WARINING", None, QtGui.QApplication.UnicodeUTF8))
        self.chkAnother.setText(QtGui.QApplication.translate("dlgAddShot", "Create another", None, QtGui.QApplication.UnicodeUTF8))
        self.butAdd.setStatusTip(QtGui.QApplication.translate("dlgAddShot", "Create Project and Directories", None, QtGui.QApplication.UnicodeUTF8))
        self.butAdd.setText(QtGui.QApplication.translate("dlgAddShot", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.butCancel.setStatusTip(QtGui.QApplication.translate("dlgAddShot", "Cancel the operation", None, QtGui.QApplication.UnicodeUTF8))
        self.butCancel.setText(QtGui.QApplication.translate("dlgAddShot", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

import epp_rc
